services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Form\Front\Customer\BillingAddressFormType:
    tags:
      - { name: form.type }

  Shopsys\ShopBundle\Form\Front\Customer\DeliveryAddressFormType:
    tags:
      - { name: form.type }

  Shopsys\ShopBundle\Form\Front\Order\PersonalInfoFormType:
    tags:
      - { name: form.type }

  Shopsys\ShopBundle\Form\Front\Order\TransportAndPaymentFormType:
    tags:
      - { name: form.type }

  Shopsys\ShopBundle\Form\Admin\Category\CategoryFormTypeExtension:
    tags:
        - { name: form.type_extension, extended_type: Shopsys\FrameworkBundle\Form\Admin\Category\CategoryFormType }
